version: "3.9"
services:
  doc:
    container_name: calendeno-v0-doc
    build:
      context: .
      dockerfile: openapi/v0/Dockerfile
    ports:
      - 18080:18080
    command: preview-docs --port=18080 --host=0.0.0.0 openapi.yaml
