version: "3.9"
services:
  app:
    container_name: calendeno-api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle/
    ports:
      - 3000:3000
    command:
      [
        "./docker/scripts/wait-for-it.sh",
        "db:3306",
        "--timeout=60",
        "--strict",
        "--",
        "bash",
        "docker/scripts/run_rails_server.sh",
      ]
    depends_on:
      - db
  db:
    container_name: calendeno-db
    image: mariadb:10.7.3
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  doc:
    container_name: calendeno-v0-doc
    build:
      context: .
      dockerfile: openapi/v0/Dockerfile
    volumes:
      - ./openapi/v0:/spec
    ports:
      - 18080:18080
    command: preview-docs --port=18080 --host=0.0.0.0 openapi.yaml
  redoc:
    volumes:
      - ./doc:/doc
    build:
      context: .
      dockerfile: doc/redoc.dockerfile
    command: redoc-cli bundle openapi.yaml -o doc/index.html

volumes:
  bundle:
