auth:
  google:
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    endpoint: https://oauth2.googleapis.com
    client_id: <%= ENV['CLIENT_ID'] %>
    client_secret: <%= ENV['CLIENT_SECRET'] %>
