name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          docker compose run app bash -c "bin/rails db:create && bundle exec rspec"
        env:
          RAILS_ENV: test
