name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: docker compose run app bundle exec rspec
        with:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
